spring:
  datasource:
    url: jdbc:h2:file:./data/currencydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    br.com.luisbottino: DEBUG