name: CI/CD Pipeline - Deploy to Heroku

on:
  push:
    branches:
      - main # Excute a pipeline when push to main branch
  pull_request:
    branches:
      - main # Run a pipeline with PRs for main branch

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout of repo code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Config java in the pipeline
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Install gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Step 4: Build project
      - name: Build
        run: ./gradlew build --no-daemon

      # Step 5: Execute tests
      - name: Run Tests
        run: ./gradlew test --no-daemon

      # Step 6: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
          heroku container:push web --app $HEROKU_APP_NAME
          heroku container:release web --app $HEROKU_APP_NAME
